update=Tuesday, 07 November 2017 'pmt' 13:41:20
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=/Library/Application Support/kicad/library
[eeschema/libraries]
LibName1=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName2=C:/Program Files/KiCad/share/kicad/library/74xx
LibName3=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName4=C:/Program Files/KiCad/share/kicad/library/actel
LibName5=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName6=C:/Program Files/KiCad/share/kicad/library/allegro
LibName7=C:/Program Files/KiCad/share/kicad/library/Altera
LibName8=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName9=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName10=C:/Program Files/KiCad/share/kicad/library/atmel
LibName11=C:/Program Files/KiCad/share/kicad/library/audio
LibName12=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName13=C:/Program Files/KiCad/share/kicad/library/bbd
LibName14=C:/Program Files/KiCad/share/kicad/library/bosch
LibName15=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName16=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName17=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName18=C:/Program Files/KiCad/share/kicad/library/conn
LibName19=C:/Program Files/KiCad/share/kicad/library/contrib
LibName20=C:/Program Files/KiCad/share/kicad/library/cypress
LibName21=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName22=C:/Program Files/KiCad/share/kicad/library/device
LibName23=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName24=C:/Program Files/KiCad/share/kicad/library/diode
LibName25=C:/Program Files/KiCad/share/kicad/library/display
LibName26=C:/Program Files/KiCad/share/kicad/library/dsp
LibName27=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName28=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName29=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName30=C:/Program Files/KiCad/share/kicad/library/gennum
LibName31=C:/Program Files/KiCad/share/kicad/library/graphic
LibName32=C:/Program Files/KiCad/share/kicad/library/hc11
LibName33=C:/Program Files/KiCad/share/kicad/library/intel
LibName34=C:/Program Files/KiCad/share/kicad/library/interface
LibName35=C:/Program Files/KiCad/share/kicad/library/ir
LibName36=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName37=C:/Program Files/KiCad/share/kicad/library/leds
LibName38=C:/Program Files/KiCad/share/kicad/library/linear
LibName39=C:/Program Files/KiCad/share/kicad/library/logo
LibName40=C:/Program Files/KiCad/share/kicad/library/maxim
LibName41=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName42=C:/Program Files/KiCad/share/kicad/library/memory
LibName43=C:/Program Files/KiCad/share/kicad/library/microchip
LibName44=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName45=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName46=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName47=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName48=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName49=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName50=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName51=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName52=C:/Program Files/KiCad/share/kicad/library/modules
LibName53=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName54=C:/Program Files/KiCad/share/kicad/library/motorola
LibName55=C:/Program Files/KiCad/share/kicad/library/motors
LibName56=C:/Program Files/KiCad/share/kicad/library/msp430
LibName57=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName58=C:/Program Files/KiCad/share/kicad/library/nxp
LibName59=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName60=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName61=C:/Program Files/KiCad/share/kicad/library/opto
LibName62=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName63=C:/Program Files/KiCad/share/kicad/library/philips
LibName64=C:/Program Files/KiCad/share/kicad/library/power
LibName65=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName66=C:/Program Files/KiCad/share/kicad/library/powerint
LibName67=C:/Program Files/KiCad/share/kicad/library/pspice
LibName68=C:/Program Files/KiCad/share/kicad/library/references
LibName69=C:/Program Files/KiCad/share/kicad/library/regul
LibName70=C:/Program Files/KiCad/share/kicad/library/relays
LibName71=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName72=C:/Program Files/KiCad/share/kicad/library/sensors
LibName73=C:/Program Files/KiCad/share/kicad/library/silabs
LibName74=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName75=C:/Program Files/KiCad/share/kicad/library/stm8
LibName76=C:/Program Files/KiCad/share/kicad/library/stm32
LibName77=C:/Program Files/KiCad/share/kicad/library/supertex
LibName78=C:/Program Files/KiCad/share/kicad/library/switches
LibName79=C:/Program Files/KiCad/share/kicad/library/texas
LibName80=C:/Program Files/KiCad/share/kicad/library/transf
LibName81=C:/Program Files/KiCad/share/kicad/library/transistors
LibName82=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName83=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName84=C:/Program Files/KiCad/share/kicad/library/valves
LibName85=C:/Program Files/KiCad/share/kicad/library/video
LibName86=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName87=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName88=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName89=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName90=C:/Program Files/KiCad/share/kicad/library/zetex
LibName91=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName92=regul
LibName93=relays
LibName94=rfcom
LibName95=sensors
LibName96=silabs
LibName97=siliconi
LibName98=stm8
LibName99=stm32
LibName100=supertex
LibName101=switches
LibName102=texas
LibName103=transf
LibName104=transistors
LibName105=triac_thyristor
LibName106=ttl_ieee
LibName107=valves
LibName108=video
LibName109=wiznet
LibName110=Worldsemi
LibName111=Xicor
LibName112=xilinx
LibName113=zetex
LibName114=Zilog
LibName115=74xgxx
LibName116=74xx
LibName117=ac-dc
LibName118=actel
LibName119=adc-dac
LibName120=allegro
LibName121=Altera
LibName122=analog_devices
LibName123=analog_switches
LibName124=atmel
LibName125=audio
LibName126=battery_management
LibName127=bbd
LibName128=bosch
LibName129=brooktre
LibName130=cmos_ieee
LibName131=cmos4000
LibName132=conn
LibName133=contrib
LibName134=cypress
LibName135=dc-dc
LibName136=device
LibName137=digital-audio
LibName138=diode
LibName139=display
LibName140=dsp
LibName141=elec-unifil
LibName142=ESD_Protection
LibName143=ftdi
LibName144=gennum
LibName145=graphic
LibName146=hc11
LibName147=intel
LibName148=interface
LibName149=intersil
LibName150=ir
LibName151=Lattice
LibName152=leds
LibName153=linear
LibName154=logo
LibName155=maxim
LibName156=mechanical
LibName157=memory
LibName158=microchip_dspic33dsc
LibName159=microchip_pic10mcu
LibName160=microchip_pic12mcu
LibName161=microchip_pic16mcu
LibName162=microchip_pic18mcu
LibName163=microchip_pic24mcu
LibName164=microchip_pic32mcu
LibName165=microchip
LibName166=microcontrollers
LibName167=modules
LibName168=motor_drivers
LibName169=motorola
LibName170=motors
LibName171=msp430
LibName172=nordicsemi
LibName173=nxp_armmcu
LibName174=nxp
LibName175=onsemi
LibName176=opto
LibName177=Oscillators
LibName178=philips
LibName179=Power_Management
LibName180=power
LibName181=powerint
LibName182=pspice
LibName183=references
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
