update=Thursday, 07 June 2018 'pmt' 14:59:50
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=
SpiceForceRefPrefix=0
SpiceUseNetNumbers=0
LabSize=60
[eeschema]
version=1
LibDir=/Library/Application Support/kicad/library
[eeschema/libraries]
LibName1=vacuumTubeEarphone-rescue
LibName2=C:/Program Files/KiCad/share/kicad/library/74xgxx
LibName3=C:/Program Files/KiCad/share/kicad/library/74xx
LibName4=C:/Program Files/KiCad/share/kicad/library/ac-dc
LibName5=C:/Program Files/KiCad/share/kicad/library/actel
LibName6=C:/Program Files/KiCad/share/kicad/library/adc-dac
LibName7=C:/Program Files/KiCad/share/kicad/library/allegro
LibName8=C:/Program Files/KiCad/share/kicad/library/Altera
LibName9=C:/Program Files/KiCad/share/kicad/library/analog_devices
LibName10=C:/Program Files/KiCad/share/kicad/library/analog_switches
LibName11=C:/Program Files/KiCad/share/kicad/library/atmel
LibName12=C:/Program Files/KiCad/share/kicad/library/audio
LibName13=C:/Program Files/KiCad/share/kicad/library/battery_management
LibName14=C:/Program Files/KiCad/share/kicad/library/bbd
LibName15=C:/Program Files/KiCad/share/kicad/library/bosch
LibName16=C:/Program Files/KiCad/share/kicad/library/brooktre
LibName17=C:/Program Files/KiCad/share/kicad/library/cmos_ieee
LibName18=C:/Program Files/KiCad/share/kicad/library/cmos4000
LibName19=C:/Program Files/KiCad/share/kicad/library/conn
LibName20=C:/Program Files/KiCad/share/kicad/library/contrib
LibName21=C:/Program Files/KiCad/share/kicad/library/cypress
LibName22=C:/Program Files/KiCad/share/kicad/library/dc-dc
LibName23=C:/Program Files/KiCad/share/kicad/library/device
LibName24=C:/Program Files/KiCad/share/kicad/library/digital-audio
LibName25=C:/Program Files/KiCad/share/kicad/library/diode
LibName26=C:/Program Files/KiCad/share/kicad/library/display
LibName27=C:/Program Files/KiCad/share/kicad/library/dsp
LibName28=C:/Program Files/KiCad/share/kicad/library/elec-unifil
LibName29=C:/Program Files/KiCad/share/kicad/library/ESD_Protection
LibName30=C:/Program Files/KiCad/share/kicad/library/ftdi
LibName31=C:/Program Files/KiCad/share/kicad/library/gennum
LibName32=C:/Program Files/KiCad/share/kicad/library/graphic
LibName33=C:/Program Files/KiCad/share/kicad/library/hc11
LibName34=C:/Program Files/KiCad/share/kicad/library/intel
LibName35=C:/Program Files/KiCad/share/kicad/library/interface
LibName36=C:/Program Files/KiCad/share/kicad/library/ir
LibName37=C:/Program Files/KiCad/share/kicad/library/Lattice
LibName38=C:/Program Files/KiCad/share/kicad/library/leds
LibName39=C:/Program Files/KiCad/share/kicad/library/linear
LibName40=C:/Program Files/KiCad/share/kicad/library/logo
LibName41=C:/Program Files/KiCad/share/kicad/library/maxim
LibName42=C:/Program Files/KiCad/share/kicad/library/mechanical
LibName43=C:/Program Files/KiCad/share/kicad/library/memory
LibName44=C:/Program Files/KiCad/share/kicad/library/microchip
LibName45=C:/Program Files/KiCad/share/kicad/library/microchip_dspic33dsc
LibName46=C:/Program Files/KiCad/share/kicad/library/microchip_pic10mcu
LibName47=C:/Program Files/KiCad/share/kicad/library/microchip_pic12mcu
LibName48=C:/Program Files/KiCad/share/kicad/library/microchip_pic16mcu
LibName49=C:/Program Files/KiCad/share/kicad/library/microchip_pic18mcu
LibName50=C:/Program Files/KiCad/share/kicad/library/microchip_pic24mcu
LibName51=C:/Program Files/KiCad/share/kicad/library/microchip_pic32mcu
LibName52=C:/Program Files/KiCad/share/kicad/library/microcontrollers
LibName53=C:/Program Files/KiCad/share/kicad/library/modules
LibName54=C:/Program Files/KiCad/share/kicad/library/motor_drivers
LibName55=C:/Program Files/KiCad/share/kicad/library/motorola
LibName56=C:/Program Files/KiCad/share/kicad/library/motors
LibName57=C:/Program Files/KiCad/share/kicad/library/msp430
LibName58=C:/Program Files/KiCad/share/kicad/library/nordicsemi
LibName59=C:/Program Files/KiCad/share/kicad/library/nxp
LibName60=C:/Program Files/KiCad/share/kicad/library/nxp_armmcu
LibName61=C:/Program Files/KiCad/share/kicad/library/onsemi
LibName62=C:/Program Files/KiCad/share/kicad/library/opto
LibName63=C:/Program Files/KiCad/share/kicad/library/Oscillators
LibName64=C:/Program Files/KiCad/share/kicad/library/philips
LibName65=C:/Program Files/KiCad/share/kicad/library/power
LibName66=C:/Program Files/KiCad/share/kicad/library/Power_Management
LibName67=C:/Program Files/KiCad/share/kicad/library/powerint
LibName68=C:/Program Files/KiCad/share/kicad/library/pspice
LibName69=C:/Program Files/KiCad/share/kicad/library/references
LibName70=C:/Program Files/KiCad/share/kicad/library/regul
LibName71=C:/Program Files/KiCad/share/kicad/library/relays
LibName72=C:/Program Files/KiCad/share/kicad/library/rfcom
LibName73=C:/Program Files/KiCad/share/kicad/library/sensors
LibName74=C:/Program Files/KiCad/share/kicad/library/silabs
LibName75=C:/Program Files/KiCad/share/kicad/library/siliconi
LibName76=C:/Program Files/KiCad/share/kicad/library/stm8
LibName77=C:/Program Files/KiCad/share/kicad/library/stm32
LibName78=C:/Program Files/KiCad/share/kicad/library/supertex
LibName79=C:/Program Files/KiCad/share/kicad/library/switches
LibName80=C:/Program Files/KiCad/share/kicad/library/texas
LibName81=C:/Program Files/KiCad/share/kicad/library/transf
LibName82=C:/Program Files/KiCad/share/kicad/library/transistors
LibName83=C:/Program Files/KiCad/share/kicad/library/triac_thyristor
LibName84=C:/Program Files/KiCad/share/kicad/library/ttl_ieee
LibName85=C:/Program Files/KiCad/share/kicad/library/valves
LibName86=C:/Program Files/KiCad/share/kicad/library/video
LibName87=C:/Program Files/KiCad/share/kicad/library/wiznet
LibName88=C:/Program Files/KiCad/share/kicad/library/Worldsemi
LibName89=C:/Program Files/KiCad/share/kicad/library/Xicor
LibName90=C:/Program Files/KiCad/share/kicad/library/xilinx
LibName91=C:/Program Files/KiCad/share/kicad/library/zetex
LibName92=C:/Program Files/KiCad/share/kicad/library/Zilog
LibName93=regul
LibName94=relays
LibName95=rfcom
LibName96=sensors
LibName97=silabs
LibName98=siliconi
LibName99=stm8
LibName100=stm32
LibName101=supertex
LibName102=switches
LibName103=texas
LibName104=transf
LibName105=transistors
LibName106=triac_thyristor
LibName107=ttl_ieee
LibName108=valves
LibName109=video
LibName110=wiznet
LibName111=Worldsemi
LibName112=Xicor
LibName113=xilinx
LibName114=zetex
LibName115=Zilog
LibName116=74xgxx
LibName117=74xx
LibName118=ac-dc
LibName119=actel
LibName120=adc-dac
LibName121=allegro
LibName122=Altera
LibName123=analog_devices
LibName124=analog_switches
LibName125=atmel
LibName126=audio
LibName127=battery_management
LibName128=bbd
LibName129=bosch
LibName130=brooktre
LibName131=cmos_ieee
LibName132=cmos4000
LibName133=conn
LibName134=contrib
LibName135=cypress
LibName136=dc-dc
LibName137=device
LibName138=digital-audio
LibName139=diode
LibName140=display
LibName141=dsp
LibName142=elec-unifil
LibName143=ESD_Protection
LibName144=ftdi
LibName145=gennum
LibName146=graphic
LibName147=hc11
LibName148=intel
LibName149=interface
LibName150=intersil
LibName151=ir
LibName152=Lattice
LibName153=leds
LibName154=linear
LibName155=logo
LibName156=maxim
LibName157=mechanical
LibName158=memory
LibName159=microchip_dspic33dsc
LibName160=microchip_pic10mcu
LibName161=microchip_pic12mcu
LibName162=microchip_pic16mcu
LibName163=microchip_pic18mcu
LibName164=microchip_pic24mcu
LibName165=microchip_pic32mcu
LibName166=microchip
LibName167=microcontrollers
LibName168=modules
LibName169=motor_drivers
LibName170=motorola
LibName171=motors
LibName172=msp430
LibName173=nordicsemi
LibName174=nxp_armmcu
LibName175=nxp
LibName176=onsemi
LibName177=opto
LibName178=Oscillators
LibName179=philips
LibName180=Power_Management
LibName181=power
LibName182=powerint
LibName183=pspice
LibName184=references
